feat(ansible): add initial roles structure and .gitignore

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -21,6 +21,7 @@ LPURPLE='\033[01;35m'
 LCYAN='\033[01;36m'
 WHITE='\033[01;37m'
 OVERWRITE='\e[1A\e[K'
+ORANGE='\033[0;33m'
 
 #emoji codes
 CHECK_MARK="${GREEN}\xE2\x9C\x94${NC}"
@@ -47,8 +48,10 @@ DOTFILES_LOG="$HOME/.dotfiles.log"
 DOTFILES_DIR="$HOME/.dotfiles"
 SSH_DIR="$HOME/.ssh"
 IS_FIRST_RUN="$HOME/.dotfiles_run"
+
+
 # _header colorize the given argument with spacing
-function __task {
+function _task {
   # if _task is called while a task was set, complete the previous
   if [[ $TASK != "" ]]; then
     printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}${TASK}\n"
@@ -57,6 +60,27 @@ function __task {
   TASK=$1
   printf "${LBLACK} [ ]  ${TASK} \n${LRED}"
 }
+
+task() {
+  # if task is called while a task was set, complete the previous
+  if [[ $TASK != "" ]]; then
+    printf "${LGREEN} [✓] ${LBLACK}${TASK}\n"
+  fi
+  # set new task title and print
+  TASK=$1
+  printf "${LBLACK} [ ] ${TASK}  ...\n${LRED}"
+}
+
+task_overwrite() {
+  # if task is called while a task was set, complete the previous
+  if [[ $TASK != "" ]]; then
+    printf "${OVERWRITE}${LGREEN} [✓]  ${LGREEN}${TASK}\n"
+  fi
+  # set new task title and print
+  TASK=$1
+  printf "${LBLACK} [ ]  ${TASK} \n${LRED}"
+}
+
 
 # _cmd performs commands with error checking
 function _cmd {
@@ -82,7 +106,60 @@ function _cmd {
   exit 1
 }
 
+__cmd() {
+  #create log if it doesn't exist
+  if ! [[ -f $DOTFILES_LOG ]]; then
+    touch $DOTFILES_LOG
+  fi
+  # empty conduro.log
+  > $DOTFILES_LOG
+  # hide stdout, on error we print and exit
+  printf "${CYAN} $1\n ${NC}"
+  if eval "$1" 1> /dev/stdout 2> $DOTFILES_LOG; then
+    #printf "\n ${LGREEN}...was sucsselful"
+    return 0 # success
+  fi
+  # read error from log and add spacing
+  printf "${OVERWRITE}${LRED} [X]  ${TASK}${LRED}\n"
+  while read line; do
+    printf "      ${line}\n"
+  done < $DOTFILES_LOG
+  printf "\n"
+  # remove log file
+  rm $DOTFILES_LOG
+  # exit installation
+  exit 1
+}
+
+__cmd_no_output() {
+  #create log if it doesn't exist
+  if ! [[ -f $DOTFILES_LOG ]]; then
+    touch $DOTFILES_LOG
+  fi
+  # empty conduro.log
+  > $DOTFILES_LOG
+  # hide stdout, on error we print and exit
+  if eval "$1" 1> /dev/null 2> $DOTFILES_LOG; then
+    return 0 # success
+  fi
+  # read error from log and add spacing
+  printf "${OVERWRITE}${LRED} [X]  ${TASK}${LRED}\n"
+  while read line; do
+    printf "      ${line}\n"
+  done < $DOTFILES_LOG
+  printf "\n"
+  # remove log file
+  rm $DOTFILES_LOG
+  # exit installation
+  exit 1
+}
+
+
 function _clear_task {
+  TASK=""
+}
+
+clear_task() {
   TASK=""
 }
 
@@ -93,112 +170,112 @@ function _task_done {
 
 function debian_setup() {
   if ! dpkg -s ansible >/dev/null 2>&1; then
-    __task "Installing Ansible"
-    _cmd "sudo apt-get update"
-    _cmd "sudo apt-get install -y software-properties-common"
-    _cmd "sudo apt-add-repository -y ppa:ansible/ansible"
-    _cmd "sudo apt-get update"
-    _cmd "sudo apt-get install -y ansible"
-    _cmd "sudo apt-get install python3-argcomplete"
-    _cmd "sudo activate-global-python-argcomplete3"
+    task "Installing Ansible"
+    __cmd "sudo apt-get update"
+    __cmd "sudo apt-get install -y software-properties-common"
+    __cmd "sudo apt-add-repository -y ppa:ansible/ansible"
+    __cmd "sudo apt-get update"
+    __cmd "sudo apt-get install -y ansible"
+    __cmd "sudo apt-get install python3-argcomplete"
+    __cmd "sudo activate-global-python-argcomplete3"
   fi
   if ! dpkg -s python3 >/dev/null 2>&1; then
-    __task "Installing Python3"
-    _cmd "sudo apt-get install -y python3"
+    task "Installing Python3"
+    __cmd "sudo apt-get install -y python3"
   fi
 
   local UBUNTU_MAJOR_VERSION=$(echo $VERSION_ID | cut -d. -f1)
   if [ $UBUNTU_MAJOR_VERSION -le 22 ]; then
     if ! dpkg -s python3-pip >/dev/null 2>&1; then
-      __task "Installing Python3 Pip"
-      _cmd "sudo apt-get install -y python3-pip"
+      task "Installing Python3 Pip"
+      __cmd "sudo apt-get install -y python3-pip"
     fi
     if ! pip3 list | grep watchdog >/dev/null 2>&1; then
-      __task "Installing Python3 Watchdog"
-      _cmd "sudo apt-get install -y python3-watchdog"
+      task "Installing Python3 Watchdog"
+      __cmd "sudo apt-get install -y python3-watchdog"
     fi
   fi
 }
 
-function arch_setup() {
-  if ! [ -x "$(command -v ansible)" ]; then
-    __task "Installing Ansible"
-    _cmd "sudo pacman -Sy --noconfirm"
-    _cmd "sudo pacman -S --noconfirm ansible"
-    _cmd "sudo pacman -S --noconfirm python-argcomplete"
-    # _cmd "sudo activate-global-python-argcomplete3"
-  fi
-  if ! pacman -Q python3 >/dev/null 2>&1; then
-    __task "Installing Python3"
-    _cmd "sudo pacman -S --noconfirm python3"
-  fi
-  if ! pacman -Q python-pip >/dev/null 2>&1; then
-    __task "Installing Python3 Pip"
-    _cmd "sudo pacman -S --noconfirm python-pip"
-  fi
-  if ! pip3 list | grep watchdog >/dev/null 2>&1; then
-    __task "Installing Python3 Watchdog"
-    _cmd "sudo pacman -S --noconfirm python-watchdog"
-  fi
+# function arch_setup() {
+#   if ! [ -x "$(command -v ansible)" ]; then
+#     _task "Installing Ansible"
+#     _cmd "sudo pacman -Sy --noconfirm"
+#     _cmd "sudo pacman -S --noconfirm ansible"
+#     _cmd "sudo pacman -S --noconfirm python-argcomplete"
+#     # _cmd "sudo activate-global-python-argcomplete3"
+#   fi
+#   if ! pacman -Q python3 >/dev/null 2>&1; then
+#     _task "Installing Python3"
+#     _cmd "sudo pacman -S --noconfirm python3"
+#   fi
+#   if ! pacman -Q python-pip >/dev/null 2>&1; then
+#     _task "Installing Python3 Pip"
+#     _cmd "sudo pacman -S --noconfirm python-pip"
+#   fi
+#   if ! pip3 list | grep watchdog >/dev/null 2>&1; then
+#     _task "Installing Python3 Watchdog"
+#     _cmd "sudo pacman -S --noconfirm python-watchdog"
+#   fi
 
-  if ! pacman -Q openssh >/dev/null 2>&1; then
-    __task "Installing OpenSSH"
-    _cmd "sudo pacman -S --noconfirm openssh"
-  fi
+#   if ! pacman -Q openssh >/dev/null 2>&1; then
+#     _task "Installing OpenSSH"
+#     _cmd "sudo pacman -S --noconfirm openssh"
+#   fi
 
-  __task "Setting Locale"
-  _cmd "sudo localectl set-locale LANG=en_US.UTF-8"
-}
+#   _task "Setting Locale"
+#   _cmd "sudo localectl set-locale LANG=en_US.UTF-8"
+# }
 
-function macos_setup() {
-  if ! [ -x "$(command -v brew)" ]; then
-    __task "Installing Homebrew"
-    _cmd "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
-  fi
-  if ! [ -x "$(command -v git)" ]; then
-    __task "Installing Git"
-    _cmd "brew install git"
-  fi
-  if ! [ -x "$(command -v ansible)" ]; then
-    __task "Installing Ansible"
-    _cmd "brew install ansible"
-  fi
-  if ! [ -x "$(command -v op)" ]; then
-    __task "Installing 1Password CLI"
-    _cmd "brew install 1password@beta"
-    _cmd "brew install 1password-cli@beta"
-    __task "Setting up 1Password CLI"
-    # press any key to continue
-    read -n 1 -s -r -p "Press any key to continue"
-    echo -e "${OVERWRITE}${OVERWRITE} [✓]  ${GREEN}1Password CLI setup complete${NC}" && _clear_task
-  fi
-}
+# function macos_setup() {
+#   if ! [ -x "$(command -v brew)" ]; then
+#     _task "Installing Homebrew"
+#     _cmd "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
+#   fi
+#   if ! [ -x "$(command -v git)" ]; then
+#     _task "Installing Git"
+#     _cmd "brew install git"
+#   fi
+#   if ! [ -x "$(command -v ansible)" ]; then
+#     _task "Installing Ansible"
+#     _cmd "brew install ansible"
+#   fi
+#   if ! [ -x "$(command -v op)" ]; then
+#     _task "Installing 1Password CLI"
+#     _cmd "brew install 1password@beta"
+#     _cmd "brew install 1password-cli@beta"
+#     _task "Setting up 1Password CLI"
+#     # press any key to continue
+#     read -n 1 -s -r -p "Press any key to continue"
+#     echo -e "${OVERWRITE}${OVERWRITE} [✓]  ${GREEN}1Password CLI setup complete${NC}" && _clear_task
+#   fi
+# }
 
 update_ansible_galaxy() {
   local os=$1
   local os_requirements=""
-  __task "Updating Ansible Galaxy"
+  task "Updating Ansible Galaxy"
   if [ -f "$DOTFILES_DIR/requirements/$os.yml" ]; then
-    __task "${OVERWRITE}Updating Ansible Galaxy with OS Config: $os"
+    task "${OVERWRITE}Updating Ansible Galaxy with OS Config: $os"
     os_requirements="$DOTFILES_DIR/requirements/$os.yml"
   fi
-  _cmd "ansible-galaxy install -r $DOTFILES_DIR/requirements/common.yml $os_requirements"
+  __cmd "ansible-galaxy install -r $DOTFILES_DIR/requirements/common.yml $os_requirements"
 }
 
-function confirmVaultAccess() {
-  __task "Checking for 1Password CLI"
-  if ! command -v op >/dev/null 2>&1; then
-    printf "${OVERWRITE} ${RED}[X]  Checking for 1Password CLI\n"
-    printf " ${WARNING}${RED}   1Password CLI is not installed.${NC}\n"
-    exit 1
-  fi
-  local op_version
-  op_version=$(op --version)
-  __task "1Password CLI found: [$op_version] -- Authenticating..."
-  if ! _cmd "op --account my.1password.com vault list"; then exit 1; fi
-  _task_done && printf "${GREEN} [✓] Successfully authenticated with 1Password CLI! ☕\n"
-  return
-}
+# function confirmVaultAccess() {
+#   __task "Checking for 1Password CLI"
+#   if ! command -v op >/dev/null 2>&1; then
+#     printf "${OVERWRITE} ${RED}[X]  Checking for 1Password CLI\n"
+#     printf " ${WARNING}${RED}   1Password CLI is not installed.${NC}\n"
+#     exit 1
+#   fi
+#   local op_version
+#   op_version=$(op --version)
+#   __task "1Password CLI found: [$op_version] -- Authenticating..."
+#   if ! _cmd "op --account my.1password.com vault list"; then exit 1; fi
+#   _task_done && printf "${GREEN} [✓] Successfully authenticated with 1Password CLI! ☕\n"
+#   return
+# }
 
 detect_os() {
   if [ -f /etc/os-release ]; then
@@ -210,7 +287,7 @@ detect_os() {
 }
 
 dotfiles_os=$(detect_os)
-__task "Loading Setup for detected OS: $dotfiles_os"
+task "Loading Setup for detected OS: $dotfiles_os"
 case $dotfiles_os in
   debian|kali|ubuntu)
     debian_setup
@@ -222,42 +299,42 @@ case $dotfiles_os in
     macos_setup
     ;;
   *)
-    __task "Unsupported OS"
-    _cmd "echo 'Unsupported OS'"
+    task "Unsupported OS"
+    __cmd "echo 'Unsupported OS'"
     ;;
 esac
 
 
-if ! [[ -f "$SSH_DIR/authorized_keys" ]]; then
-  __task "Generating SSH keys"
-  _cmd "mkdir -p $SSH_DIR"
-  _cmd "chmod 700 $SSH_DIR"
-  _cmd "ssh-keygen -b 4096 -t rsa -f $SSH_DIR/id_rsa -N '' -C $USER@$HOSTNAME"
-  _cmd "cat $SSH_DIR/id_rsa.pub >> $SSH_DIR/authorized_keys"
-fi
+# if ! [[ -f "$SSH_DIR/authorized_keys" ]]; then
+#   __task "Generating SSH keys"
+#   _cmd "mkdir -p $SSH_DIR"
+#   _cmd "chmod 700 $SSH_DIR"
+#   _cmd "ssh-keygen -b 4096 -t rsa -f $SSH_DIR/id_rsa -N '' -C $USER@$HOSTNAME"
+#   _cmd "cat $SSH_DIR/id_rsa.pub >> $SSH_DIR/authorized_keys"
+# fi
 
-if ! [[ -d "$DOTFILES_DIR" ]]; then
-  __task "Cloning repository"
-  _cmd "git clone --quiet https://github.com/mbriesemeister/dotfiles.git $DOTFILES_DIR"
-else
-  __task "Updating repository"
-  _cmd "git -C $DOTFILES_DIR pull --quiet"
-fi
+# if ! [[ -d "$DOTFILES_DIR" ]]; then
+#   __task "Cloning repository"
+#   _cmd "git clone --quiet https://github.com/mbriesemeister/dotfiles.git $DOTFILES_DIR"
+# else
+#   __task "Updating repository"
+#   _cmd "git -C $DOTFILES_DIR pull --quiet"
+# fi
 
-pushd "$DOTFILES_DIR" 2>&1 > /dev/null
+# pushd "$DOTFILES_DIR" 2>&1 > /dev/null
 update_ansible_galaxy $ID
 
-# confirmVaultAccess
+## confirmVaultAccess
 
-rm -f $VAULT_SECRET_FILE
-ansible-playbook "$DOTFILES_DIR/main.yml" "$@"
+# rm -f $VAULT_SECRET_FILE
+# ansible-playbook "$DOTFILES_DIR/main.yml" "$@"
 
-popd 2>&1 > /dev/null
+# popd 2>&1 > /dev/null
 
-if ! [[ -f "$IS_FIRST_RUN" ]]; then
-  echo -e "${CHECK_MARK} ${GREEN}First run complete!${NC}"
-  echo -e "${ARROW} ${CYAN}Please reboot your computer to complete the setup.${NC}"
-  touch "$IS_FIRST_RUN"
-fi
+# if ! [[ -f "$IS_FIRST_RUN" ]]; then
+#   echo -e "${CHECK_MARK} ${GREEN}First run complete!${NC}"
+#   echo -e "${ARROW} ${CYAN}Please reboot your computer to complete the setup.${NC}"
+#   touch "$IS_FIRST_RUN"
+# fi
 
 # vi:ft=sh:
